Repository De-cal/6-Snack-FE, pull requests merged in 2025-08, with the labels that each got.

#207 feat: 찜 목록 페이지 구현, 모달 남은 금액 로직 수정 [이태빈]
  next.config.ts
  src/app/(main)/my/favorites/page.tsx
  src/app/(preview)/components-preview/navigationLinks.ts
  src/app/(preview)/components-preview/page.tsx
  src/assets/icons/ic_dot.svg
  src/assets/images/img_bucket_logo.png
  src/assets/images/img_dog_logo.png
  src/components/common/OrderManageModal.tsx
  src/lib/api/favorite.api.ts
  src/types/favorite.types.ts
Labels: Refactor, QA

#201 refactor:order manage QA 진행 및 리팩토링 [김우주]
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(preview)/components-preview/page.tsx
  src/assets/icons/ic_no_order.svg
  src/components/common/OrderManageModal.tsx
  src/components/common/RequestList.tsx
  src/components/ui/Badge.tsx
  src/components/ui/Button.tsx
  src/hooks/useOrderVisibleCount.ts
  src/hooks/usePendingOrders.ts
  src/lib/api/orderManage.api.ts
Labels: Refactor, QA

#211 chore: fetchClient BASE_URL 수정 [이태빈]
  src/lib/api/fetchClient.api.ts
Labels: API, Chore

#212 refactor: middleware.ts 파일명 변경으로 설정 활성화
  src/middleware.ts
Labels: Bug, Refactor

#214 fix: cookieFetch 오류수정 [이지수B]
  src/app/error/page.tsx
  src/lib/api/fetchClient.api.ts
Labels: Bug

#221 feat: 찜 목록 페이지 무한 스크롤 구현 [이태빈]
  package-lock.json
  package.json
  src/app/(main)/my/favorites/page.tsx
  src/lib/api/favorite.api.ts
  src/types/favorite.types.ts
Labels: Feature

#213 refactor/feat : 회원관리 QA 진행 및 구매 요청관리 컴페니 별로 호출 할 수 있게 변경 [김우주]
  src/app/(main)/manage/users/_components/User.tsx
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(main)/profile/_components/ProfileForm.tsx
  src/components/common/DeleteAccountConfirmModal.tsx
  src/components/common/Input.tsx
  src/components/common/InviteMemberModal.tsx
  src/components/common/MemberList.tsx
  src/components/common/OrderManageModal.tsx
  src/components/common/RequestList.tsx
  src/components/common/Toast.tsx
  src/components/ui/SearchBar.tsx
  src/lib/api/invite.api.ts
  src/lib/api/superAdmin.api.ts
  src/types/inviteMemberModal.types.ts
Labels: Bug, Refactor, QA

#227 fix: 프로필 슈퍼 어드민이 아닐때 기업명이 안나오는 버그 수정 [김우주]
  src/app/(main)/profile/_components/ProfileForm.tsx
Labels: Bug

#197 QA: 최고관리자 회원가입 개선사항 적용 [김홍섭]
  src/app/(auth)/signup/super-admin/page.tsx
Labels: Refactor, QA

#223 feat: Zustand로 order 정보 관리, orderId 타입 변경, svg 컴포넌트 수정 [이태빈]
  src/app/(main)/cart/order/_components/OrderPageContent.tsx
  src/app/(main)/cart/page.tsx
  src/components/common/RequestList.tsx
  src/components/svg/CheckIconSvg.tsx
  src/components/svg/ExclamationMarkIconSvg.tsx
  src/lib/api/orderManage.api.ts
  src/stores/orderStore.ts
  src/types/order.types.ts
Labels: Feature, Refactor

#224 feat: 토스페이먼츠 결제 모듈 페이지 구현 [이태빈]
  src/app/(toss-payments)/checkout/page.tsx
  src/app/(toss-payments)/fail/page.tsx
  src/app/(toss-payments)/success/page.tsx
Labels: Feature, UI

#235 fix: 빌드 오류 수정 [김홍섭]
  src/app/(auth)/signup/super-admin/page.tsx
Labels: Bug

#240 feat:웹 접근성 개선
  src/app/(auth)/signup/[inviteId]/page.tsx
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/app/(main)/products/_components/ProductsPageContent.tsx
Labels: Refactor

#236 refactor: 웹 접근성 고려 코드 리팩터링, 센트리 적용 [이태빈]
  .gitignore
  next.config.ts
  package-lock.json
  package.json
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(auth)/login/_components/FormErrorMessage.tsx
  src/app/(auth)/login/page.tsx
  src/app/(main)/cart/order/_components/OrderPageContent.tsx
  src/app/(main)/cart/page.tsx
  src/app/(main)/my/favorites/page.tsx
  src/app/(main)/my/products/page.tsx
  src/app/(toss-payments)/checkout/page.tsx
  src/app/(toss-payments)/fail/page.tsx
  src/app/(toss-payments)/success/page.tsx
  src/app/error/page.tsx
  src/app/global-error.tsx
  src/components/common/TextArea.tsx
  src/components/common/Toast.tsx
  src/components/ui/Button.tsx
  src/instrumentation-client.ts
  src/instrumentation.ts
Labels: Bug, Refactor

#241 QA: httpOnly 쿠키 기반 자동 토큰 재발급 로직 및 인증 상태 확인 개선
  src/lib/api/fetchClient.api.ts
  src/providers/AuthProvider.tsx
Labels: Feature, QA

#237 feat: 역할별 접근제어 및 에러페이지 리디렉션 추가
  src/middleware.ts
Labels: Feature

#234 refactor: 상품 목록 페이지 & 상품 등록 모달 QA 반영 [이지수B]
  src/app/(main)/products/_components/SubCategoryTabs.tsx
  src/components/common/DropDown.tsx
  src/components/common/ProductDetail/CategoryNavigation.tsx
  src/components/common/ProductGrid.tsx
  src/components/common/ProductRegistrationForm.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/hooks/useProductRegistrationForm.ts
  src/lib/schemas/product.schema.ts
Labels: Refactor, QA

#238 refactor: 웹 접근성 추가 및 회원 관리에서 서치 사용시 페이지네이션 버그 수정 [김우주]
  src/app/(main)/manage/users/_components/User.tsx
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(main)/order-manage/page.tsx
  src/app/(main)/profile/_components/ProfileField.tsx
  src/app/(main)/profile/_components/ProfileForm.tsx
  src/app/(main)/profile/_components/ProfilePasswordSection.tsx
  src/app/(main)/profile/_components/ProfileSubmitButton.tsx
  src/components/common/InviteMemberModal.tsx
  src/components/common/OrderManageModal.tsx
  src/components/common/RequestList.tsx
Labels: Bug, Refactor

#243 chore: 미들웨어 주석처리 (임시)
  src/middlewareBS.ts
Labels: Chore

#245 fix: 최고관리자 회원가입 폼 입력시 버튼 활성화 오류 해결
  src/app/(auth)/signup/super-admin/page.tsx
  src/components/common/Input.tsx
Labels: Bug

#244 fix: 시멘틱 태그 수정 [김우주]
  src/components/common/RequestList.tsx
Labels: Refactor

#251 refactor: XIconSvg 기본 cursor-pointer 설정 제거 [이지수B]
  src/components/svg/XIconSvg.tsx
Labels: Refactor

#250 feat:상품상세페이지에 찜하기 기능을 추가하였습니다 [조성빈]
  src/components/common/ProductDetail.tsx
  src/components/common/ProductDetail/CartAndLikeButtons.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/components/svg/LikeIconSvg.tsx
  src/hooks/useToggleFavorite.ts
  src/types/productDetail.types.ts
Labels: Feature

#248 fix: order ui 수정, 페이지네이션 수정/ 프로필 비밀번호 ui 수정 [김우주]
  src/app/(main)/manage/users/_components/User.tsx
  src/app/(main)/profile/_components/ProfilePasswordSection.tsx
  src/components/common/OrderManageModal.tsx
  src/components/common/RequestList.tsx
  src/hooks/usePendingOrders.ts
  src/lib/api/orderManage.api.ts
Labels: Bug, Refactor

#254 refactor: 즉시 구매 시 구매 내역 확인 invalidQueries 적용 [이태빈]
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/cart/page.tsx
Labels: Refactor, QA

#249 refactor: 관리자 구매내역확인 "즉시 요청"->"즉시 구매"로 변경, useBudgets 쿼리 키 "companyId" 추가 및 staleTime 제거 [김홍섭]
  src/app/(main)/order-history/page.tsx
  src/hooks/useBudgets.ts
Labels: Chore

#247 feat: 맡은 각 주요 페이지에 로딩 스피너 적용 [김홍섭]
  src/app/(auth)/signup/super-admin/page.tsx
  src/app/(main)/manage/budgets/page.tsx
  src/app/(main)/order-history/page.tsx
Labels: UI

#256 fix: 프로필 기업명 수정될 수 있게 변경 [김우주]
  src/app/(main)/manage/users/_components/User.tsx
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(main)/profile/_components/ProfileForm.tsx
  src/components/ui/SearchBar.tsx
  src/lib/api/orderManage.api.ts
Labels: Bug, Refactor

#257 refactor: spinner 수정 [이태빈]
  src/app/(preview)/components-preview/page.tsx
  src/app/globals.css
  src/assets/images/img_dog_in_bucket.png
  src/assets/images/img_dog_with_logo.png
  src/components/common/DogSpinner.tsx
Labels: UI, Refactor

#258 fix: "구매내역확인" 페이지 모의발표 핫픽스 개선 [김홍섭]
  src/app/(main)/order-history/page.tsx
  src/hooks/useOrderHistory.ts
Labels: Feature, Bug, UI

#261 hotfix: 찜하기 버튼 border영역 까지 클릭 가능하게 수정 및 내 구매요청 내역 주문 금액에 배송비 포함 [조성빈]
  src/app/(main)/my/order-list/page.tsx
  src/components/common/ProductDetail/CartAndLikeButtons.tsx
Labels: Refactor

#260 fix: 여러 자잘한 에러, 오타 수정, 불필요한 코드 삭제 [이태빈]
  src/app/(main)/cart/page.tsx
  src/app/(toss-payments)/checkout/page.tsx
  src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
  src/app/(toss-payments)/success/page.tsx
  src/components/common/DogSpinner.tsx
  src/providers/AuthProvider.tsx
Labels: Refactor, QA

#262 refactor: 유저 구매요청 승인부분 토스 결제 모듈 연동 및 자잘한 수정 [이태빈]
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(toss-payments)/checkout/page.tsx
  src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
  src/components/common/OrderManageModal.tsx
  src/hooks/useDeleteProduct.ts
  src/lib/api/orderManage.api.ts
  src/types/cart.types.ts
  src/types/order.types.ts
Labels: Feature, Refactor

#263 fix: 버셀 빌드 오류 해결 [이태빈]
  src/app/(main)/cart/order/_components/OrderPageContent.tsx
Labels: Bug

#266 fix: 호버박스 파란테두리 제거
  src/app/(main)/order-history/page.tsx
Labels: UI

#265 feat: 핫픽스 관련 개선사항 적용 (상품리스트 페이지 & 관리자 구매요청 관리상세 페이지) [이지수B]
  components.json
  package-lock.json
  package.json
  src/app/(main)/manage/budgets/page.tsx
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/app/(main)/products/_components/ProductsPageContent.tsx
  src/app/globals.css
  src/components/common/ProductDetail/CategoryNavigation.tsx
  src/components/common/ProductGrid.tsx
  src/components/common/ProductGridSkeleton.tsx
  src/components/common/Toast.tsx
  src/components/svg/ExclamationMarkIconSvg.tsx
  src/components/ui/skeleton.tsx
  src/hooks/useOrderStatusUpdate.ts
  src/lib/utils.ts
Labels: Bug, Refactor

#267 refactor: queryKey 변경, Toast 오류 해결, gitkeep 삭제 [이태빈]
  src/app/(auth)/signup/super-admin/page.tsx
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/cart/page.tsx
  src/app/(main)/manage/budgets/_components/BudgetFormUI.tsx
  src/app/(main)/manage/users/_components/User.tsx
  src/app/(main)/my/order-list/[orderId]/_components/.gitkeep
  src/app/(main)/my/order-list/_components/.gitkeep
  src/app/(main)/my/order-list/page.tsx
  src/app/(main)/order-manage/[orderId]/_components/.gitkeep
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(main)/products/[productId]/_components/.gitkeep
  src/app/(main)/profile/_components/ProfileForm.tsx
  src/app/(preview)/components-preview/MockData.ts
  src/app/(preview)/components-preview/page.tsx
  src/components/common/InviteMemberModal.tsx
  src/components/common/ProductDetail.tsx
  src/hooks/useDeleteProduct.ts
Labels: Chore, Refactor

#269 fix: 타입 에러 해결... [이태빈]
  src/components/common/ProductGrid.tsx
  src/types/product.types.ts
Labels: Bug

#273 fix: 이메일 유효성 검사 및 토스트 z인덱스 수정 [김우주]
  src/app/(main)/profile/_components/ProfileForm.tsx
  src/components/common/InviteMemberModal.tsx
  src/components/common/Toast.tsx
  src/lib/schemas/email.schema.ts
Labels: Bug, Refactor

#276 refactor: 찜 목록, 로그인, 로그아웃 수정 [이태빈]
  src/app/(auth)/login/page.tsx
  src/app/(main)/my/favorites/page.tsx
  src/providers/AuthProvider.tsx
Labels: Refactor

#278 feat: 상품 목록 초기 데이터 로딩 시 최신순으로 정렬 [김홍섭]
  src/app/(main)/order-history/page.tsx
  src/hooks/useOrderHistory.ts
Labels: Feature, Bug

#279 feat: 미들웨어 역할별 접근제어 설정 추가, 글로벌 에러 페이지 추가
  src/app/error.tsx
  src/middleware.ts
Labels: Feature, Bug

#284 fix: 미들웨어 긴급 케이스1
  src/middleware.ts
Labels: Bug

#286 fix: config 매처 주석
  src/middleware.ts
Labels: Bug

#288 fix: 미들웨어 경로 구체화
  src/middleware.ts
Labels: Bug

#289 fix: 컨픽 아예 빼기
  src/middleware.ts
Labels: Bug

#290 fix: 미들웨어 오류 다시
  src/middleware.ts
Labels: Bug

#291 fix: 케이스3
  src/middleware.ts
Labels: Bug

#293 fix: 새 매처
  src/middleware.ts
Labels: Bug

#294 fix: 로그인,회원가입 빼기
  src/middleware.ts
Labels: Bug

#295 Refactor/order manage detail
  src/app/(auth)/signup/[inviteId]/page.tsx
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/components/common/MobileCategoryMenu.tsx
  src/components/common/ProductDetail.tsx
  src/components/common/ProductGrid.tsx
  src/components/common/SubCategoryItem.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/components/layout/Header.tsx
  src/components/svg/ResetIconSvg.tsx
  src/hooks/useCurrentSubCategory.ts
  src/hooks/useToggleFavorite.ts
  src/lib/schemas/inviteSignupSchema.ts
Labels: Bug, Refactor, QA

#297 fix: 미들웨어 해제
  src/middleware_BACKUP.ts
Labels: Bug

#296 fix: 안쓰는 프롭스 제거 - 빌드에러 해결 [이지수B]
  src/app/(main)/products/[productId]/page.tsx
Labels: Bug

#299 fix: 미들웨어 활성화
  src/middleware.ts
Labels: Bug

#302 feat: 챗봇 기능(버튼&채팅창) 추가, openai 라이브러리 설치 및 연결
  package-lock.json
  package.json
  src/app/(auth)/signup/super-admin/page.tsx
  src/app/api/chat/route.ts
  src/app/error/page.tsx
  src/app/layout.tsx
  src/components/chatbot/ChatWindow.tsx
  src/components/chatbot/Chatbot.tsx
  src/components/chatbot/FloatingButton.tsx
  src/components/common/SubCategoryItem.tsx
  src/hooks/useChat.ts
  src/types/chat.types.ts
Labels: Feature

#303 feat: 로딩 스피너 처리 및 자잘한 수정 [이태빈]
  src/app/(auth)/login/page.tsx
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/cart/order/_components/OrderItem.tsx
  src/app/(main)/my/favorites/page.tsx
  src/app/(toss-payments)/checkout/page.tsx
  src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
Labels: Feature, Refactor

#304 refactor: 디자인 UI 개선 [이지수B]
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/app/(main)/products/_components/ProductsPageContent.tsx
  src/components/common/SideMenu.tsx
  src/components/common/SubCategoryItem.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/types/auth.types.ts
Labels: Refactor

#308 style: 챗봇 플로팅버튼, 채팅창 스타일 개선 [김홍섭]
  src/components/chatbot/ChatWindow.tsx
  src/components/chatbot/FloatingButton.tsx
  src/hooks/useChat.ts
Labels: UI

#312 refactor: 스키마 변경에 따른 payment 페이지 변경 [이태빈]
  src/app/(main)/cart/page.tsx
  src/app/(toss-payments)/checkout/page.tsx
  src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
  src/types/order.types.ts
Labels: Refactor

#313 fix: 챗봇&플로팅버튼 스타일 문법 오류 수정
  src/components/chatbot/ChatWindow.tsx
  src/components/chatbot/FloatingButton.tsx
Labels: UI, Refactor

#315 feat: 결제 모듈 부족한 점 추가 [이태빈]
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(toss-payments)/fail/_components/FailPageContent.tsx
  src/app/(toss-payments)/success/_components/SuccessPageContent.tsx
  src/components/common/OrderManageModal.tsx
  src/lib/api/orderManage.api.ts
  src/types/order.types.ts
Labels: Feature

#316 refactor: 구매요청관리 상세 페이지 미세 UI 개선, 스켈레톤 적용 [이지수B]
  src/app/(main)/order-history/[orderId]/page.tsx
  src/app/(main)/order-manage/[orderId]/_components/OrderDetailSkeleton.tsx
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/lib/utils/formatDate.util.ts
Labels: UI, Refactor

#318 hotfix:상품상세 페이지 수정, 내 구매요청내역 페이지 instant_approved받을 수 있게 수정 [조성빈]
  src/app/(main)/products/_components/FlashToastConsumer.tsx
  src/stores/flashToast.ts
Labels: Bug, Refactor

#319 hotfix: 변경사항 적용안된거 다시pr [조성빈]
  src/app/(main)/my/order-list/page.tsx
  src/app/(main)/products/page.tsx
  src/components/common/MenuDropdown.tsx
  src/components/common/MyRequestList.tsx
  src/components/common/ProductDetail.tsx
  src/components/common/ProductDetail/ProductActions.tsx
  src/components/common/ProductDetail/ProductImage.tsx
  src/lib/utils/convertStatus.util.ts
Labels: Chore, Refactor, QA

#320 feat: SameSite Strict 대신 Lax 사용하도록 수정 [김홍섭]
  src/lib/utils/cookie.util.ts
Labels: Bug

#322 fix: 회원 관리에 나온 오류 수정 [김우주]
  src/app/(main)/manage/users/_components/User.tsx
  src/components/common/MemberList.tsx
  src/components/ui/Badge.tsx
  src/lib/api/fetchClient.api.ts
Labels: Bug

#324 핫픽스 2차: 문제 해결 PR (이슈 목록 중 미들웨어 이슈 제외) [김홍섭]
  src/app/(main)/order-history/page.tsx
  src/components/chatbot/ChatWindow.tsx
  src/components/chatbot/FloatingButton.tsx
  src/hooks/useOrderHistory.ts
Labels: Feature, Bug

#326 핫픽스 2단계: middleware 액세스토큰 재발급 이슈 해결 [김홍섭]
  src/middleware.ts
  src/middleware_BACKUP.ts
Labels: Refactor

#329 hotfix:스키마 변경에 따른 주문금액 NaN으로 출력되는 현상 수정 [조성빈]
  src/app/(main)/my/order-list/page.tsx
  src/types/myOrderList.types.ts
Labels: Bug, QA

#323 fix: 회원가입 페이지 핫픽스 개선 [이지수B]
  src/app/(auth)/signup/[inviteId]/page.tsx
Labels: Refactor, QA

#330 feat: /manage/users, /manage/budgets 경로에 대해 USER, ADMIN 접근 차단 (SUPER_ADMIN만 허용) [김홍섭]
  src/middleware.ts
Labels: Feature, Bug

#331 hotfix: 랜딩페이지 여백 추가 및 이미지 png 에서 webp로 교체 [조성빈]
  src/app/page.tsx
  src/assets/images/landing/landingPage_desktop.webp
  src/assets/images/landing/landingPage_mobile.webp
  src/assets/images/landing/landingPage_tablet.webp
Labels: Refactor

#332 fix: 3000원 추가로 표시하는 오류 개선, mx-auto max-w-xxxpx 삭제 [김홍섭]
  src/app/(main)/order-history/page.tsx
Labels: Feature, Bug

#335 feat: 시계 svg로 추가했습니다[김우주]
  src/components/svg/TimeIconSvg.tsx
  src/components/ui/Badge.tsx
Labels: UI

#336 refactor: NoContent 컴포넌트 props 수정 [이태빈]
  src/components/common/NoContent.tsx
Labels: UI, Refactor

#338 fix: Prev와 Next 버튼 색상 일치, NoContent Props 사용으로 UI 개선
  src/app/(main)/order-history/page.tsx
Labels: Refactor

#339 feat: 결제에서 사용자가 취소 시 되돌리는 함수 추가 [이태빈]
  src/app/(toss-payments)/checkout/page.tsx
  src/hooks/usePreventLeave.ts
Labels: Feature

#353 refactor: 모바일 카테고리 드롭다운, 상품등록 폼 디자인 개선 [이지수B]
  src/components/common/MobileCategoryMenu.tsx
  src/components/common/ProductRegistrationForm.tsx
Labels: Bug, Refactor
