Repository De-cal/6-Snack-FE, pull requests merged in 2025-07, with the labels that each got.

#2 chore: 개발용 nav바 추가,공통 컴포넌트 테스트용 페이지 추가, TextArea공통 컴포넌트 추가
  src/app/(preview)/components-preview/page.tsx
  src/app/layout.tsx
  src/components/common/TextArea.tsx
  src/components/preview/DevNavBar.tsx
  src/constants/navigationLinks.ts
  src/types/textArea.types.ts
Labels: Feature, Chore

#3 chore: 기초적인 파일들 업로드 및 수정 [이태빈]
  src/app/layout.tsx
  src/components/common/Desktop.tsx
  src/components/common/Mobile.tsx
  src/components/common/Tablet.tsx
  src/types/children.types.ts
Labels: Chore

#4 feat:memberlist 컴포넌트 추가[조성빈]
  src/app/(preview)/components-preview/page.tsx
  src/components/common/MemberList.tsx
  src/types/meberList.types.ts
Labels: Feature, UI

#7 feat:드롭다운 공통컴포넌트 구현[조성빈]
  src/app/(preview)/components-preview/page.tsx
  src/components/common/DropDown.tsx
Labels: Feature, UI

#8 feat: 토스트 구현 [조성빈]
  src/app/(preview)/components-preview/page.tsx
  src/assets/icons/ic_!_red.svg
  src/assets/icons/icon_X_gray.svg
  src/components/common/Toast.tsx
Labels: Feature, UI

#12 Feat/사이드메뉴,서브카테고리메뉴,페이지네이션 공통컴포넌트 UI 구현 [장원빈]
  src/app/example/page.tsx
  src/app/page.tsx
  src/components/common/Pagination.tsx
  src/components/common/SideMenu.tsx
  src/components/common/SubCategoryMenu.tsx
  src/components/common/examples/PaginationExample.tsx
  src/components/common/examples/SideMenuExample.tsx
  src/components/common/examples/SubCategoryMenuExamples.tsx
  src/svg/ArrowIcon.tsx
  src/svg/XIcon.tsx
  src/types/pagination.types.ts
  src/types/sideMenu.types.ts
  src/types/subCategoryMenu.types.ts
Labels: Feature, UI, Refactor, Test

#11 chore:textArea, memberList, dropDown, toast컴포넌트 global css 반영, 반응형 반영[조성빈]
  src/app/(preview)/components-preview/page.tsx
  src/assets/icons/ic_X_gray.svg
  src/assets/icons/ic_check_white.svg
  src/assets/icons/ic_exclamation_red.svg
  src/components/common/DropDown.tsx
  src/components/common/MemberList.tsx
  src/components/common/TextArea.tsx
  src/components/common/Toast.tsx
  src/types/meberList.types.ts
  src/types/textArea.types.ts
  src/types/toast.types.ts
Labels: Chore, Refactor

#13 feat:서치 컴포넌트 Ui 구현 [김우주]
  src/app/(preview)/components-preview/page.tsx
  src/components/ui/SearchBar.tsx
  src/types/serchBar.types.ts
Labels: Feature, UI

#17 feat: subCategoryMenu 공통 컴포넌트 1차 UI 완성 [이태빈]
  src/app/(preview)/components-preview/page.tsx
  src/assets/icons/ic_chevron_down_gray.svg
  src/assets/icons/ic_chevron_up_gray.svg
  src/assets/icons/ic_exclamation_mark.svg
  src/assets/icons/ic_exclamation_mark_red.svg
  src/assets/icons/ic_x_gray.svg
  src/components/common/OrderRequestModal.tsx
  src/components/common/Pagination.tsx
  src/components/common/SideMenu.tsx
  src/components/common/SubCategoryItem.tsx
  src/components/common/SubCategoryMenu.tsx
  src/components/common/Toast.tsx
  src/components/svg/ArrowIcon.tsx
  src/components/svg/CheckIcon.tsx
  src/components/svg/XIcon.tsx
  src/components/ui/.gitkeep
Labels: Feature, UI

#28 feat: 공용 컴포넌트 Menu & TabMenu UI 제작 [이지수B]
  src/app/(preview)/components-preview/page.tsx
  src/components/common/Menu.tsx
  src/components/common/TabMenu.tsx
  src/components/svg/BudgetIconSvg.tsx
  src/components/svg/FilledUserIconSvg.tsx
  src/components/svg/UserIconSvg.tsx
Labels: UI

#27 refactor: 모달 프로바이더 닫기 옵션(esc, 백드롭 클릭) 추가, ProductList 이미지 수정 [이태빈]
  src/components/common/ProductList.tsx
  src/providers/ModalProvider.tsx
Labels: Feature, UI, Refactor

#29 refactor : 버튼 컴포넌트 리팩토링 [김우주]
  src/app/(main)/profile/_components/.gitkeep
  src/app/(preview)/components-preview/page.tsx
  src/components/ui/Badge.tsx
  src/components/ui/Button.tsx
  src/components/ui/Card.tsx
  src/components/ui/SearchBar.tsx
  src/types/button.types.ts
Labels: Chore, Refactor

#40 feat: `예산 폼/최고관리자 예산/구매 내역 확인` 컴포넌트&페이지 UI 구현; 리팩터링 개선 필수(MVP 우선); [김홍섭]
  src/app/(main)/budgets/super-admin/_components/BudgetForm.tsx
  src/app/(main)/budgets/super-admin/page.tsx
  src/app/(main)/order-history/_components/.gitkeep
  src/app/(main)/order-history/_components/PurchaseList.tsx
  src/app/(main)/order-history/_components/PurchaseSummary.tsx
  src/app/(main)/order-history/page.tsx
  src/constants/navigationLinks.ts
Labels: Feature, UI

#43 feat: 구매 요청 승인/반려 모달 1차 UI 완성 [이태빈]
  src/app/(preview)/components-preview/page.tsx
  src/app/globals.css
  src/components/common/OrderManageModal.tsx
  src/components/common/OrderRequestModal.tsx
  src/components/common/SubCategoryItem.tsx
Labels: Feature, UI

#46 fix: 글로벌 css 오류 해결 및 BudgetIconSvg 오류 해결 [이태빈]
  src/app/globals.css
  src/components/svg/BudgetIconSvg.tsx
Labels: Bug

#49 chore: 불필요한 import 제거, 개발용 NavBar 경로 수정 [이태빈]
  .github/ISSUE_TEMPLATE/QA_template.md
  src/components/common/SubCategoryItem.tsx
  src/constants/navigationLinks.ts
Labels: Chore, Refactor

#52 fix:드롭다운 컴포넌트가 시안과 다르게 rounded가 적용되있던 현상 수정[조성빈]
  src/components/common/DropDown.tsx
Labels: Bug, Chore, Refactor

#61 fix: 오류 해결, import 중복 제거 [이태빈]
  src/app/(preview)/components-preview/page.tsx
  src/components/layout/GeneralLayout.tsx
Labels: Bug, Chore

#56 feat:상품 상세페이지 ui 구현 및 추가 [조성빈]
  src/app/(main)/products/[productId]/page.tsx
Labels: Feature, UI

#66 refactor: RequestList 피드백 반영 [이태빈]
  src/app/(preview)/components-preview/page.tsx
  src/components/common/RequestList.tsx
Labels: Feature, UI, Refactor

#67 feat: 상품 등록 내역 페이지 1차 UI 완성 [이태빈]
  src/app/(main)/my/products/page.tsx
  src/components/common/ProductList.tsx
Labels: Feature, UI

#72 feat: 헤더 Link 추가, 프론트엔드 경로 수정 [이지수B]
  src/app/(main)/budgets/super-admin/_components/BudgetForm.tsx
  src/app/(main)/budgets/super-admin/page.tsx
  src/app/(main)/manage/budgets/page.tsx
  src/app/(main)/manage/layout.tsx
  src/app/(main)/manage/users/page.tsx
  src/app/(main)/users/super-admin/_components/.gitkeep
  src/app/(main)/users/super-admin/page.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/components/layout/GuestHeader.tsx
  src/components/layout/Header.tsx
  src/components/svg/LikeIconSvg.tsx
  src/components/svg/VerticalBarIconSvg.tsx
Labels: Feature, UI

#75 refactor: subCategoryItem 컴포넌트 수정 [이태빈]
  src/components/common/SubCategoryItem.tsx
Labels: UI, Refactor

#77 chore: 개발자 도구 수정 [이태빈]
  src/components/preview/DevNavBar.tsx
  src/components/preview/types.ts
  src/constants/navigationLinks.ts
Labels: Feature, Chore, UI

#81 refactor: 빈 페이지 rfc 스니펙 적용, Devtools 카테고리 정렬 추가 [이태빈]
  src/app/(main)/cart/order-confirmed/page.tsx
  src/app/(main)/cart/page.tsx
  src/app/(main)/products/page.tsx
  src/components/preview/DevNavBar.tsx
Labels: Chore, Refactor

#79 feat: 로그인 및 회원가입 페이지에 유효성 검사 및 상태 관리 추가; AuthProvider로 감싸기 [김홍섭]
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/signup/super-admin/_components/SignUpForm.tsx
  src/app/(auth)/signup/super-admin/page.tsx
  src/app/(main)/budgets/super-admin/page.tsx
  src/app/(main)/manage/layout.tsx
  src/app/Providers.tsx
  src/app/actions/adminSignUp.ts
  src/app/actions/auth.ts
  src/app/products/[productId]/_components/.gitkeep
  src/app/products/[productId]/page.tsx
  src/app/products/_components/.gitkeep
  src/components/layout/AuthenticatedHeader.tsx
  src/components/layout/GuestHeader.tsx
  src/components/layout/Header.tsx
  src/components/svg/product-modal/CancelBtn.tsx
  src/components/svg/product-modal/InputText.tsx
  src/components/svg/product-modal/ModifyBtn.tsx
  src/components/svg/product-modal/ProductImage.tsx
  src/components/svg/product-modal/RegisterBtn.tsx
  src/lib/api/auth.api.ts
  src/lib/api/fetchClient.api.ts
  src/lib/api/user.api.ts
  src/lib/schemas/signUpSchema.ts
  src/lib/utils/cookies.ts
  src/middleware.ts
  src/providers/AuthProvider.tsx
Labels: Feature, Refactor

#80 feat: Header UI 완료 & AuthProvider 전역 적용 [이지수B]
  src/app/(auth)/signup/[inviteId]/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/products/page.tsx
  src/assets/images/img_logo.webp
  src/components/common/MobileCategoryMenu.tsx
  src/components/common/SideMenu.tsx
  src/components/common/SubCategoryItem.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/components/layout/GuestHeader.tsx
  src/components/layout/Header.tsx
  src/components/svg/FilledUserIconSvg.tsx
  src/components/svg/HamburgerMenuIconSvg.tsx
  src/components/svg/UserIconSvg.tsx
  src/lib/api/.gitkeep
  src/lib/api/auth.api.ts
  src/lib/api/fetchClient.api.ts
  src/lib/api/invite.api.ts
Labels: Feature

#90 refactor: ProductList 공통 컴포넌트 2차 기능 리팩터링 [이태빈]
  package-lock.json
  package.json
  src/app/(main)/my/products/page.tsx
  src/app/(preview)/components-preview/PreviewMockData.ts
  src/app/(preview)/components-preview/page.tsx
  src/components/common/ProductList.tsx
  src/components/preview/DevNavBar.tsx
Labels: Feature, Refactor

#92 feat: OrderManageModal 2차 기능 리팩터링 [이태빈]
  src/app/(main)/my/products/page.tsx
  src/app/(main)/order-manage/_components/Order.tsx
  src/app/(preview)/components-preview/MockData.ts
  src/app/(preview)/components-preview/page.tsx
  src/components/common/OrderManageModal.tsx
Labels: Feature, Refactor

#93 feat: 로그인 백엔드 연동(로그인 기능만 일단 간단하게 구현) [이태빈]
  .env.example
  src/app/(auth)/login/page.tsx
Labels: API, Feature, Refactor

#95 feat: 일반, 관리자 회원가입 로그인페이지 (모바일 UI완성) + API 연동 [이지수B]
  src/app/(auth)/signup/[inviteId]/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/components/layout/GuestHeader.tsx
  src/components/layout/Header.tsx
  src/lib/api/auth.api.ts
  src/lib/api/invite.api.ts
Labels: Feature, UI

#97 Revert "refactor : 구매 요청 상세 페이지 피드백 반영 및 페이지네이션 공통 컴포넌트 이슈 해결"
  .gitignore
  src/app/(main)/order-history/[orderId]/page.tsx
  src/app/(main)/order-history/_components/PurchaseList.tsx
  src/lib/api/orderHistory.api.ts
Labels: Refactor

#96 feat: profile API 연동 [김우주]
  src/app/(main)/profile/_components/ProfileComponent.tsx
  src/components/ui/Button.tsx
  src/lib/api/profile.api.ts
Labels: Feature

#101 chore: DateFormat 이름 변경, Devtools 업데이트, ReactQuery 설치 및 설정 [이태빈]
  package-lock.json
  package.json
  src/app/(auth)/signup/super-admin/_components/SignUpForm.tsx
  src/app/(preview)/components-preview/DevTools.tsx
  src/app/(preview)/components-preview/navigationLinks.ts
  src/app/(preview)/components-preview/types.ts
  src/app/Providers.tsx
  src/app/actions/adminSignUp.ts
  src/app/layout.tsx
  src/components/common/ProductList.tsx
  src/components/common/RequestList.tsx
  src/lib/schemas/signup.schema.ts
  src/lib/utils/formatDate.util.ts
  src/middleware_BACKUP.ts
  src/providers/QueryProvider.tsx
Labels: Chore, Refactor

#99 feat: 일반 유저, 관리자 회원가입 페이지 UI 반응형 & API 연동 [이지수B]
  src/app/(auth)/signup/[inviteId]/page.tsx
Labels: Feature, UI

#102 fix:랜딩 페이지 반응형 구현 및 css 수정 [조성빈]
  public/images/img_landing.svg
  public/images/landingPage_desktop.png
  public/images/landingPage_mobile.png
  public/images/landingPage_tablet.png
  src/app/globals.css
  src/app/page.tsx
  src/components/layout/GeneralLayout.tsx
Labels: Feature, Bug, UI

#106 feat: 예산관리/구매내역확인/최고관리자회원가입 API연결; 디자인 다듬기; [김홍섭]
  src/app/(auth)/signup/super-admin/page.tsx
  src/app/(main)/manage/budgets/_components/BudgetFormUI.tsx
  src/app/(main)/manage/budgets/page.tsx
  src/app/(main)/order-history/_components/PurchaseList.tsx
  src/app/(main)/order-history/_components/PurchaseSummary.tsx
  src/app/(main)/order-history/page.tsx
  src/components/common/FloatingLabelInput.tsx
  src/components/common/Input.tsx
  src/components/common/LabeledInput.tsx
  src/components/common/ProductRegistrationForm.tsx
  src/lib/schemas/signup.schema.ts
Labels: API, Feature, Refactor

#109 feat: 주문 상세 페이지에 장바구니 다시 담기 기능 구현 [장원빈]
  src/app/(main)/my/order-list/[orderId]/page.tsx
Labels: Feature

#110 feat: 상품 등록 내역 2차 기능 구현 완료 [이태빈]
  src/app/(main)/my/products/page.tsx
  src/components/common/DropDown.tsx
  src/lib/api/product.api.ts
  src/types/product.types.ts
Labels: Feature, Refactor

#111 feat: 공통컴포넌트-상품등록 모달 UI개선
  src/assets/icons/ic_photo.svg
  src/components/common/ProductRegistrationForm.tsx
Labels: UI, Refactor

#115 feat:구매 요청관리 및 프로필 조금 리팩토링 [김우주]
  src/app/(main)/order-manage/_components/Order.tsx
  src/components/common/OrderManageModal.tsx
  src/components/common/RequestList.tsx
  src/lib/api/orderManage.api.ts
  src/types/Order.types.ts
Labels: Feature, Refactor

#116 feat: 장바구니 페이지 2차 기능 구현 완료 [이태빈]
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/cart/_components/CartItemQuantityDropdown.tsx
  src/app/(main)/cart/page.tsx
  src/app/(main)/my/products/page.tsx
  src/app/(preview)/components-preview/navigationLinks.ts
  src/lib/api/cart.api.ts
  src/lib/api/product.api.ts
  src/types/cart.types.ts
  src/types/product.types.ts
Labels: API, Feature

#118 feat: 상품 리스트 페이지 Tanstack Query 마이그레이션 및 Zustand로 전역변수 관리 [이지수B]
  package-lock.json
  package.json
  src/app/(main)/products/_components/ProductsPageContent.tsx
  src/components/common/DropDown.tsx
  src/components/common/MobileCategoryMenu.tsx
  src/components/common/ProductDetail/CategoryNavigation.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/hooks/useProducts.ts
  src/lib/api/fetchClient.api.ts
  src/lib/api/product.api.ts
  src/stores/categoryStore.ts
  src/types/product.types.ts
Labels: Feature

#127 feat: 장바구니 관리자 페이지 3차 기능 중간 커밋 [이태빈]
  package-lock.json
  package.json
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/cart/page.tsx
  src/lib/api/order.api.ts
  src/types/order.types.ts
Labels: Feature, Refactor

#128 refactor: 디바이스 타입 판별 커스텀 훅으로 분리, 토스트 모달 수정, 수량 드롭다운 수정 [이태빈]
  src/app/(main)/my/products/page.tsx
  src/app/(main)/products/_components/ProductsPageContent.tsx
  src/components/common/QuantityDropdown.tsx
  src/components/common/Toast.tsx
  src/hooks/useDeviceType.ts
Labels: Feature, Refactor

#131 refactor: 장바구니 페이지(유저, 관리자 입장) 3차 기능 구현 완료 [이태빈]
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/cart/order/_components/OrderPageContent.tsx
  src/app/(main)/cart/page.tsx
  src/components/common/Toast.tsx
Labels: Feature, Refactor

#133 feat: 관리자 주문요청 관리 페이지 구현 [이지수B]
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/hooks/useOrderDetail.ts
  src/lib/api/orderDetail.api.ts
  src/types/order.types.ts
Labels: API, Feature

#136 refactor: 맡은 컴포넌트와 함수에 대해 린팅 오류 개선사항 적용 [김홍섭]
  src/app/(auth)/signup/super-admin/page.tsx
  src/app/(main)/manage/budgets/_components/BudgetFormUI.tsx
  src/app/(main)/order-history/[orderId]/page.tsx
  src/app/(main)/order-history/page.tsx
  src/hooks/useOrderHistory.ts
Labels: Bug, Chore, Refactor

#137 fix: npm run build 에러 해결 [이지수B]
  next.config.ts
  src/app/(auth)/signup/[inviteId]/page.tsx
  src/app/(main)/order-manage/[orderId]/page.tsx
  src/app/(main)/products/_components/ProductsPageContent.tsx
  src/components/common/ProductRegistrationForm.tsx
  src/lib/api/fetchClient.api.ts
Labels: Bug

#135 fix: 엄격 모드에서 발생하는 build 오류 해결 [이태빈]
  src/app/(preview)/components-preview/DevTools.tsx
  src/components/common/QuantityDropdown.tsx
  src/lib/api/order.api.ts
Labels: Bug

#140 next config 수정 [이태빈]
  next.config.ts
Labels: Chore, Refactor

#141 feat:나의 구매요청 내역 페이지 구현 [조성빈]
  src/app/(main)/my/order-list/page.tsx
  src/components/common/MyRequestList.tsx
  src/components/common/ProductDetail.tsx
  src/components/ui/Badge.tsx
  src/lib/api/myOrderList.api.ts
  src/lib/utils/converStatus.util.ts
  src/types/myOrderList.types.ts
Labels: Feature

#145 refactor: 주문 확인 페이지로 이동 시 URL에 동적 파라미터로 orderId 넘겨줌 [이태빈]
  src/app/(main)/cart/order-confirmed/[orderId]/page.tsx
  src/app/(main)/cart/order-confirmed/_components/.gitkeep
  src/app/(main)/cart/order/_components/OrderPageContent.tsx
  src/app/(main)/cart/page.tsx
  src/lib/api/order.api.ts
  src/types/order.types.ts
Labels: Feature, Refactor

#146 fix:상품상세페이지에 subCategoryItem적용, 좋아요버튼 및 상품수정기능 주석처리[조성빈]
  src/app/(main)/products/[productId]/page.tsx
  src/components/common/MenuDropdown.tsx
  src/components/common/MobileCategoryMenu.tsx
  src/components/common/ProductDetail.tsx
  src/components/common/ProductDetail/CartAndLikeButtons.tsx
  src/components/common/ProductDetail/ProductActions.tsx
  src/components/common/SubCategoryItem.tsx
  src/components/layout/AuthenticatedHeader.tsx
  src/hooks/useCurrentSubCategory.ts
Labels: Feature, Bug, Refactor

#144 refactor: 최고관리자 구매내역확인 페이지에서 피드백 수정사항 반영
  src/app/(main)/order-history/page.tsx
  src/hooks/useAdminOrders.ts
  src/hooks/useOrderHistory.ts
Labels: Bug, UI, Refactor

#152 chore: 진행도 업데이트 [이태빈]
  src/app/(preview)/components-preview/navigationLinks.ts
Labels: Chore

#153 feat:spinner 추가 [조성빈]
  public/images/spinner_img.png
  public/images/spinner_img2.png
  src/app/(preview)/components-preview/page.tsx
  src/components/common/spinnerAnimate.tsx
Labels: Feature, Chore

#155 refactor: 로그인 페이지에서 인풋 공통 컴포넌트 추출 및 최고관리자 회원가입 페이지에 적용
  src/app/(auth)/signup/super-admin/page.tsx
  src/components/common/Input.tsx
Labels: UI, Refactor

#162 refactor: 로그인 버튼 비활성화 QA 반영 [이태빈]
  src/app/(auth)/login/page.tsx
Labels: Feature, Refactor, QA

#161 refactor: 예산 관리 UI/UX 및 타입 안정성 개선 [김홍섭]
  src/app/(main)/manage/budgets/_components/BudgetFormUI.tsx
  src/app/(main)/manage/budgets/page.tsx
  src/lib/api/budgets.api.ts
Labels: UI, Refactor, QA

#165 feat: 상품리스트 페이지 오류 개선 + 상품 판매갯수 적용 [이지수B]
  src/app/(main)/products/_components/ProductsPageContent.tsx
  src/components/common/DropDown.tsx
  src/components/common/ProductGrid.tsx
  src/components/common/ProductRegistrationForm.tsx
  src/hooks/useProductsInfinite.ts
  src/types/product.types.ts
Labels: Feature, Bug

#166 feat: 주문 내역 상세 페이지 디자인 개선,린팅 오류 수정 [장원빈]
  src/app/(main)/cart/order-confirmed/[orderId]/page.tsx
  src/app/(main)/my/order-list/[orderId]/page.tsx
  src/app/(main)/order-history/[orderId]/page.tsx
  src/app/(preview)/components-preview/page.tsx
  src/components/common/InviteMemberModal.tsx
  src/components/common/Pagination.tsx
  src/components/common/SubCategoryMenu.tsx
  src/components/common/examples/InviteMemberModalExample.tsx
  src/components/common/examples/PaginationExample.tsx
  src/components/common/examples/SideMenuExample.tsx
  src/components/common/examples/SubCategoryMenuExamples.tsx
Labels: Refactor

#171 fix: 빌드 에러 수정 [이태빈]
  src/app/(main)/cart/_components/CartItem.tsx
  src/app/(main)/cart/order/_components/OrderItem.tsx
  src/components/common/OrderManageModal.tsx
  src/components/common/RequestList.tsx
Labels: Bug, Refactor

#172 build: 맡은 파일들에 대한 esLint 빌드 문법오류 수정 [김홍섭]
  src/components/common/Input.tsx
  src/hooks/useAdminOrders.ts
  src/hooks/useOrderHistory.ts
  src/lib/api/auth.api.ts
  src/lib/api/fetchClient.api.ts
Labels: Bug, Chore

#174 QA: 팀 컨벤션 관련 팀원 전체 QA 진행 [이태빈]
  src/components/common/ConfirmationModal.tsx
  src/components/common/DropDown.tsx
  src/components/common/FloatingLabelInput.tsx
  src/components/common/Input.tsx
  src/components/common/LabeledInput.tsx
  src/components/common/MemberList.tsx
  src/components/common/MyRequestList.tsx
  src/components/common/ProductDetail.tsx
  src/components/common/ProductDetail/CartAndLikeButtons.tsx
  src/components/common/ProductDetail/ProductBasicInfo.tsx
  src/components/common/ProductDetail/ProductImage.tsx
  src/components/common/ProductEditForm.tsx
  src/components/common/ProductGrid.tsx
  src/components/common/ProductRegistrationForm.tsx
  src/components/common/ProfileAvatar.tsx
  src/components/common/spinnerAnimate.tsx
  src/components/ui/Badge.tsx
  src/components/ui/Card.tsx
  src/components/ui/SearchBar.tsx
  src/hooks/useAdminOrders.ts
  src/hooks/useOrderHistory.ts
  src/hooks/useOrderVisibleCount.tsx
  src/hooks/useProductDetail.tsx
  src/lib/api/addToCart.api.ts
  src/lib/api/companyUser.api.ts
  src/lib/api/invite.api.ts
  src/lib/api/myOrderList.api.ts
  src/lib/api/orderDetail.api.ts
  src/lib/api/orderHistory.api.ts
  src/lib/api/orderManage.api.ts
  src/lib/api/productDetail.api.ts
  src/lib/api/profile.api.ts
  src/lib/api/superAdmin.api.ts
  src/lib/utils/categories.util.ts
  src/lib/utils/cookies.ts
  src/providers/AuthProvider.tsx
  src/types/Badge.types.ts
  src/types/InviteMemberModal.types.ts
  src/types/meberList.types.ts
  src/types/productDetail.types.ts
  src/types/textArea.types.ts
  src/types/toast.types.ts
Labels: QA

#178 QA: 우주님 프론트엔트 코드리뷰 주석 추가 [이태빈]
  src/app/(main)/manage/users/_components/User.tsx
  src/app/(main)/order-manage/_components/Order.tsx
Labels: QA

#173 refactor:랜딩페이지, 상품상세페이지 리팩터링[조성빈]
  src/app/(main)/my/order-list/page.tsx
  src/app/(main)/products/[productId]/page.tsx
  src/app/page.tsx
  src/components/common/ConfirmationModal.tsx
  src/components/common/ProductDetail.tsx
  src/components/common/ProductDetail/ProductActions.tsx
  src/components/common/ProductDetail/ProductBasicInfo.tsx
  src/hooks/useDeleteProduct.ts
  src/hooks/useProductDetail.ts
  src/lib/api/deleteProduct.api.ts
  src/types/myOrderList.types.ts
  src/types/productDetail.types.ts
Labels: Feature, Bug, Refactor

#183 fix: 태빈님이 남겨주신 QA를 반영하였습니다 [조성빈]
  src/app/(preview)/components-preview/page.tsx
  src/components/common/DogSpinner.tsx
  src/components/common/DropDown.tsx
  src/components/common/MyRequestList.tsx
  src/components/common/ProductDetail.tsx
  src/components/common/ProductDetail/CartAndLikeButtons.tsx
  src/components/common/ProductDetail/ProductBasicInfo.tsx
  src/components/common/ProductDetail/ProductImage.tsx
  src/components/common/Toast.tsx
  src/lib/api/addToCart.api.ts
  src/types/meberList.types.ts
  src/types/productDetail.types.ts
  src/types/toast.types.ts
Labels: Bug, Chore

#185 fix: @rakaso598 수정사항 - `export default function으로 변경` 적용
  src/components/common/ConfirmationModal.tsx
Labels: Chore, Refactor

#182 refacotr: 내 구매 요청 내역 및 구매 완료료 디자인 개선 및 새 응답에 맞게 수정 [장원빈]
  src/app/(main)/cart/order-confirmed/[orderId]/page.tsx
  src/app/(main)/my/order-list/[orderId]/page.tsx
  src/app/(main)/order-history/[orderId]/page.tsx
  src/lib/api/orderHistory.api.ts
Labels: Refactor

#193 refactor:주문 완료 메시지 관리자/일반유저 구분 [장원빈]
  src/app/(main)/cart/order-confirmed/[orderId]/page.tsx
Labels: Refactor

#194 fix:state 타입 정의 [김우주]
  src/components/common/InviteMemberModal.tsx
Labels: Refactor

#191 refactor: 장바구니 페이지에서 관리자 이상일 때 버튼 텍스트 수정, 장바구니 주문 페이지 비활성화 중 텍스트 수정 [이태빈]
  src/app/(main)/cart/order/_components/OrderPageContent.tsx
  src/app/(main)/cart/page.tsx
Labels: UI, QA

#199 QA: 구매 내역 확인 개선사항 적용 [김홍섭]
  src/app/(main)/order-history/page.tsx
Labels: Refactor, QA

#204 feat: 내 구매 요청 내역 페이지에서 상품명을 클릭시 내 구매 요청 내역 상세 페이지로 이동하는 기능 추가[조성빈]
  src/app/(main)/my/order-list/page.tsx
  src/components/common/MyRequestList.tsx
Labels: Feature
